export const ProductActionType = Object.freeze({
    FETCH_PRODUCT_REQUEST: "@@FILES/FETCH_PRODUCT_REQUEST",
    FETCH_PRODUCT_SUCCESS: "@@FILES/FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAILURE: "@@FILES/FETCH_PRODUCT_FAILURE",
  });

  export const ProductCategoryActionType = Object.freeze({
    FETCH_PRODUCT_CATEGORY_REQUEST: "@@FILES/FETCH_PRODUCT_CATEGORY_REQUEST",
    FETCH_PRODUCT_CATEGORY_SUCCESS: "@@FILES/FETCH_PRODUCT_CATEGORY_SUCCESS",
    FETCH_PRODUCT_CATEGORY_FAILURE: "@@FILES/FETCH_PRODUCT_CATEGORY_FAILURE",
  });

  export const ProductFilterCategoryActionType = Object.freeze({
    FETCH_PRODUCT_CATEGORY_FILTER_REQUEST: "@@FILES/FETCH_PRODUCT_CATEGORY_FILTER_REQUEST",
    FETCH_PRODUCT_CATEGORY_FILTER_SUCCESS: "@@FILES/FETCH_PRODUCT_CATEGORY_FILTER_SUCCESS",
    FETCH_PRODUCT_CATEGORY_FILTER_FAILURE: "@@FILES/FETCH_PRODUCT_CATEGORY_FILTER_FAILURE",
  });

  export const ProductSearchFilterActionType = Object.freeze({
    FETCH_PRODUCT_SEARCH_FILTER_REQUEST: "@@FILES/FETCH_PRODUCT_SEARCH_FILTER_REQUEST",
    FETCH_PRODUCT_SEARCH_FILTER_SUCCESS: "@@FILES/FETCH_PRODUCT_SEARCH_FILTER_SUCCESS",
    FETCH_PRODUCT_SEARCH_FILTER_FAILURE: "@@FILES/FETCH_PRODUCT_SEARCH_FILTER_FAILURE",
  });